version: '3.8'

services:
  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    env_file:
      - ./project/.env
    depends_on:   
      - mongodb
      - redis
  
  mongodb:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=optideploy
    volumes:
      - mongodbdata:/data/db

  worker:
    build: ./project
    command: celery --app=app.main.celery worker --loglevel=info --logfile=app/workers/worker_logs/celery.log
    env_file:
      - ./project/.env
    depends_on:
      - mongodb
      - redis

  redis:
    image: redis:6-alpine

  flower:
    build: ./project
    command: sh -c "/usr/src/app/start_flower.sh"
    ports:
      - 5556:5555
    env_file:
      - ./project/.env
    depends_on:
      - redis
      - worker

volumes: 
  mongodbdata:

