version: '3.8'

services:
  web:
    build: ./project
    command: gunicorn -k uvicorn.workers.UvicornWorker -c app/config.py app.main:app
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    env_file:
      - ./project/.env
    depends_on:   
      - mongodb
      - redis
      - rabbitmq
    logging:
      driver: syslog
      options:
        syslog-address: "tcp+tls://${PAPERTRAIL_URL}"
        tag: "{{.Name}}/{{.ID}}"
  
  mongodb:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 27017
    env_file:
      - ./project/.env
    volumes:
      - mongodbdata:/data/db

  worker:
    build: ./project
    command: celery --app=app.main.celery worker --loglevel=info 
    env_file:
      - ./project/.env
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    logging:
      driver: syslog
      options:
        syslog-address: "tcp+tls://${PAPERTRAIL_URL}"
        tag: "{{.Name}}/{{.ID}}"

  redis:
    image: redis:6-alpine

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    env_file:
      - ./project/.env
    ports:
      - 5672:5672
      - 15672:15672

  flower:
    build: ./project
    command: sh -c "/usr/src/app/start_flower.sh"
    ports:
      - 5556:5555
    env_file:
      - ./project/.env
    depends_on:
      - redis
      - worker
      - rabbitmq

volumes: 
  mongodbdata:

