version: '3.8'

services:
  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8004:8000
    env_file:
      - ./project/.env
    depends_on:   
      - mongodb
      - redis
  
  mongodb:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=optideploy

  worker:
    build: ./project
    command: celery --app=app.worker.celery worker --loglevel=info --logfile=app/worker_logs/celery.log
    volumes: 
      - ./project:/usr/src/app
    env_file:
      - ./project/.env
    depends_on:
      - mongodb
      - redis

  redis:
    image: redis:6-alpine

  dashboard:
    build: ./project
    command:  celery --app=app.worker.celery --broker=redis://redis:6379/0 flower --port=5555 
    ports:
      - 5556:5555
    env_file:
      - ./project/.env
    depends_on:
      - redis
      - worker
      - mongodb

