name: Continuous Integration

on: [push, pull_request]

env:
  WEB_IMAGE: optideploy_web
  DB_IMAGE: optideploy_db

jobs:

  test:
    name: Quality Checks and Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort bandit safety
      - name: Flake8
        run: flake8 --max-line-length 199
      - name: Black
        run: black . --check
      - name: isort
        run: isort . --check-only
      - name: bandit
        run: bandit .
      - name: safety
        run: safety check
      - name: Spin up containers
        run: docker-compose up -d --build
      - name: Run Tests
        run: docker-compose exec -T web python -m pytest .