name: Continuous Integration

on: [push]

jobs:

  build:
    name: Build, Test and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2.3.4
      - name: Build images
        run: docker-compose -f docker-compose.yml build
      - name: Pytest
        run: docker-compose exec web python -m pytest .
      # - name: Push images
      #   run: |
      #     docker push ${{ env.WEB_IMAGE }}:latest
      #     docker push ${{ env.DB_IMAGE }}:latest