name: Continuous Integration

on: [push]

env:
  PAPERTRAIL_URL: ${{ secrets.PAPERTRAIL_URL }}

jobs:

  build:
    name: Build, Test and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2.3.4
      - name: Spin up containers
        run: docker-compose up -d --build
      - name: Pytest
        run: docker exec web python -m pytest .
      # - name: Push images
      #   run: |
      #     docker push ${{ env.WEB_IMAGE }}:latest
      #     docker push ${{ env.DB_IMAGE }}:latest