name: Continuous Integration

on: [push]

env:
  PAPERTRAIL_URL: ${{ secrets.PAPERTRAIL_URL }}

jobs:

  build:
    name: Build, Test and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2.3.4
      - name: Spin up containers
        run: docker-compose up -d --build
      - name: Pytest
        run: docker-compose exec -T web python -m pytest .
      - name: Flake8
        run: docker-compose exec -T web python -m flake8 --max-line-length 199
      - name: Black
        run: ddocker-compose exec -T  web python -m black . --check
      - name: isort
        run: docker-compose exec -T  web python -m isort . --check-only